import { useThemeContext } from '@/contexts/ThemeProvider'
import { Html, Head, Main, NextScript } from 'next/document'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    apple: "/icon.png"
  },
  themeColor: '#000000'
}
export default function Document() {

  return (
    <Html lang="en">
      <Head title='FitCount'>
        <meta name="description" content="Fit Count" />
        <meta name="manifest" content="/manifest.json" />
        <meta name='theme-color' content='#F4F7FE' />
        <link rel="manifest" href="/manifest.json"/>
      </Head>

      <body className={'bg-[#F4F7FE] h-screen dark:bg-[#02081B]'}  >
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
